version: "3.5"
services:
  grocery_product_api:
    container_name: "grocery_product_api"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: grocery_product_api
    ports:
      - 0.0.0.0:3500:3500
#  db:
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
